In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score, precision_score
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer

In [3]:
df = pd.read_csv("HousingData.csv")
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,NaN,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,NaN,2.5050,1,273,21.0,396.90,7.88,11.9

In [16]:
## on supprime les lignes ou le prix est fixÃ© Ã  50k (donnÃ©es erronÃ© d'aprÃ¨s l'Ã©nnonceÃ©)

df = df.loc[df["MEDV"] != 50]
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,NaN,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,NaN,2.5050,1,273,21.0,396.90,7.88,11.9

In [21]:
np.sum(df.isna())

## CRIM --> taux de criminalitÃ© - remplacer nan par la valeur moyenne
## ZN --> propotion de zone rÃ©sidentielle - remplacer par la valeur moyenne
## INDUS --> proportion d'entrerpise 
## CHAS --> variable binaire (prÃ©sence ou non de la riviere)


## AGE --> propotion de maison occupÃ© prÃ© annÃ©es 40 occupÃ© par des proprietaires 
## LSTAT --> proportion de status infÃ©rieur dans la populaiton

CRIM       19
ZN         19
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        18
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT      20
MEDV        0
dtype: int64

In [43]:
## CHAS  :

np.sum(df["CHAS"] == 1) / np.sum(df["CHAS"] == 0)

## 6% des appart sont proche de la riviere

0.06334841628959276

In [51]:
df[df["CHAS"] == 1]

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
142,3.32105,0.0,19.58,1.0,0.8710,5.403,100.0,1.3216,5,403,14.7,396.90,26.82,13.4
154,1.41385,0.0,19.58,1.0,0.8710,6.129,96.0,1.7494,5,403,14.7,321.02,15.12,17.0
155,3.53501,0.0,19.58,1.0,0.8710,6.152,NaN,1.7455,5,403,14.7,88.01,15.02,15.6
160,1.27346,0.0,19.58,1.0,0.6050,6.250,92.6,1.7984,5,403,14.7,338.92,5.50,27.0
208,0.13587,0.0,10.59,1.0,0.4890,6.064,59.1,4.2392,4,277,18.6,381.32,14.66,24.4
209,0.43571,0.0,10.59,1.0,0.4890,5.344,100.0,3.8750,4,277,18.6,396.90,23.09,20.0
210,0.17446,NaN,10.59,1.0,0.4890,5.960,92.1,3.8771,4,277,18.6,393.25,17.27,21.7
211,0.37578,0.0,10.59,1.0,0.4890,5.404,88.6,3.6650,4,277,18.6,395.24,23.98,19.3
212,0.21719,0.0,10.59,1.0,0.4890,5.807,53.8,3.6526,4,277,18.6,390.94,16.03,22.4
216,0.04560,0.0,13.89,1.0,0.5500,5.888,56.0,3.1121,5,276,16.4,392.80,13.51,23.3
218,0.11069,0.0,13.89,1.0,0.5500,5.951,93.8,2.8893,5,276,16.4,396.90,17.92,21.5
219,0.11425,0.0,NaN,1.0,0.5500,6.373,92.4,3.3633,5,276,16.4,393.74,10.50,23.0
220,0.35809,0.0,6.20,1.0,0.5070,6.951,88.5,2.8617,8,307,17.4,391.70,9.71,26.7
221,0.40771,0.0,6.20,1.0,0.5070,6.164,91.3,3.0480,8,307,17.4,395.24,21.46,21.7
222,0.62356,0.0,6.20,1.0,0.5070,6.879,77.7,3.2721,8,307,17.4,390.39,9.93,27.5
234,0.44791,0.0,6.20,1.0,0.5070,6.726,66.5,3.6519,8,307,17.4,360.20,8.05,29.0
236,NaN,0.0,6.20,1.0,0.5070,6.631,76.5,4.1480,8,307,17.4,388.45,9.54,25.1
269,0.09065,20.0,6.96,1.0,0.4640,5.920,61.5,3.9175,3,223,18.6,391.34,13.65,20.7
273,0.22188,20.0,6.96,1.0,0.4640,7.691,51.8,4.3665,3,223,18.6,390.77,6.58,35.2
274,0.05644,40.0,6.41,1.0,0.4470,6.758,32.9,4.0776,4,254,17.6,396.90,3.53,32.4
276,0.10469,40.0,6.41,1.0,0.4470,7.267,49.0,4.7872,4,254,17.6,389.25,6.05,33.2
277,0.06127,40.0,6.41,1.0,0.4470,6.826,27.6,4.8628,4,254,17.6,393.45,NaN,33.1
282,0.06129,20.0,3.33,1.0,0.4429,7.645,49.7,5.2119,5,216,14.9,377.07,3.01,46.0
356,8.98296,0.0,18.10,1.0,0.7700,6.212,97.4,2.1222,24,666,20.2,377.73,17.60,17.8
357,3.84970,0.0,18.10,1.0,0.7700,6.395,91.0,2.5052,24,666,20.2,391.34,13.27,21.7
358,5.20177,0.0,18.10,1.0,0.7700,6.127,83.4,2.7227,24,666,20.2,395.43,11.48,22.7
363,4.22239,0.0,18.10,1.0,0.7700,5.803,89.0,1.9047,24,666,20.2,353.04,14.64,16.8
364,3.47428,0.0,18.10,1.0,0.7180,8.780,82.9,1.9047,24,666,20.2,354.55,5.29,21.9

In [57]:
mean_chas = df[df["CHAS"] == 1].mean()
mean_chas

CRIM         1.456204
ZN           6.666667
INDUS       11.741852
CHAS         1.000000
NOX          0.584211
RM           6.410714
AGE         75.596296
DIS          3.237614
RAD          8.500000
TAX        361.214286
PTRATIO     17.639286
B          372.242500
LSTAT       13.081852
MEDV        24.289286
dtype: float64